version: 2.1
# Use a package of configuration called an orb.
orbs:
    aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
commands: 
  destroy_environment:
    steps:
      - run: 
          name: Destroy environment
          command: | 
            aws cloudformation delete --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}
jobs:
    smoke_test_simulate: 
      docker: 
        - image: amazon/aws-cli
      steps: 
        - checkout 
        - run: 
            name: simulate error
            command: |
              return 1
        - destroy_environment
          when: on_fail                 

# Sequential workflow
workflows:
    build-infra:
      jobs:
        # - build
        # - create_infrastructure
        # - configure_infrastructure
        - smoke_test_simulate