---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "remove unnecessary dependencies"
  become: true
  apt: 
    autoremove: yes 

- name: Install Node.js and npm
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: Install PM2
  become: true
  npm:
    name: pm2
    global: yes

- name: "create a web directory if it does not exist"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: a+rwx

- name: "copy index test page file"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes

- name: "start a server"
  shell: pm2 start ~/web/index.js -f